apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-credentials
  namespace: default
spec:
  vaultAuthRef: default
  mount: kvv2
  type: kv-v2
  path: admin-credentials
  refreshAfter: 1h
  destination:
    name: admin-credentials
    create: true
  data:
    data:
      username: "admin"
      password: "P@ssw0rd_S3cure_Compl3x_8q71KLpn"
