apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-creds
  namespace: vault
spec:
  type: kv-v2                              # Specify KV store version
  mount: secret                            # KV secrets engine mount path
  path: admin-creds                        # Path where the secret is stored
  vaultAuthRef: default                    # Reference to the VaultAuth CR
  destination:
    name: admin-creds                      # Name of the K8s Secret to create
    create: true                           # Create the Secret if it doesn't exist
    type: Opaque                           # Secret type (Opaque is default)
