# SA for frontend secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-vault-sa
  namespace: frontend
---
# Vault auth for frontend secrets
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: frontend-vault-auth
  namespace: frontend
spec:
  allowedNamespaces:
  - frontend
  kubernetes:
    role: frontend-vault-reader
    serviceAccount: frontend-vault-sa
    tokenExpirationSeconds: 600
  method: kubernetes
  mount: kubernetes
  namespace: frontend
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: frontend-creds
  namespace: frontend
spec:
  type: kv-v2                               # Specify KV store version
  mount: secret                             # KV secrets engine mount path
  path: applications/frontend/frontend-creds # Path where the secret is stored
  vaultAuthRef: frontend-vault-auth         # Reference to the VaultAuth CR
  refreshAfter: 10s
  destination:
    name: frontend-creds                    # Name of the K8s Secret to create
    create: true                            # Create the Secret if it doesn't exist
    type: Opaque                            # Secret type (Opaque is default)
