# SA for backend secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-vault-sa
  namespace: backend
---
# Vault auth for backend secrets
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: backend-vault-auth
  namespace: vault
spec:
  allowedNamespaces:
  - backend
  kubernetes:
    role: backend-vault-reader
    serviceAccount: backend-vault-sa
    tokenExpirationSeconds: 600
  method: kubernetes
  mount: kubernetes
  namespace: backend
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: backend-creds
  namespace: backend
spec:
  type: kv-v2                                # Specify KV store version
  mount: secret                              # KV secrets engine mount path
  path: applications/backend/backend-creds # Path where the secret is stored
  vaultAuthRef: vault/backend-vault-auth    # Reference to the VaultAuth CR
  refreshAfter: 2h
  destination:
    name: backend-creds                     # Name of the K8s Secret to create
    create: true                             # Create the Secret if it doesn't exist
    type: Opaque                             # Secret type (Opaque is default)
---
# # Create policy and role for backend in Vault pod:


# # Enable Kubernetes auth if not already enabled
# vault auth enable kubernetes
# vault write auth/kubernetes/config kubernetes_host="https://kubernetes.default.svc.cluster.local:443"

# # Create policy to all secrets in /applications/backend/* path
# vault policy write backend-read - <<EOF
# path "secret/data/applications/backend/*" {
#   capabilities = ["read"]
# }
# EOF

# # Create the role for the Vault Secrets Operator
# vault write auth/kubernetes/role/backend-vault-reader \
#     bound_service_account_names=backend-vault-sa \
#     bound_service_account_namespaces=backend \
#     policies=backend-read \
#     ttl=1h
