{{- if .Values.letsencryptStagingCertificate.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-01-staging
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-01-staging
    solvers:
      - http01:
          ingress:
            ingressClassName: external-nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-default-crt-letsencrypt-staging
  namespace: cert-manager
spec:
  secretName: wildcard-tls-letsencrypt-staging
  dnsNames:
  - "*.{{ .Values.global.domain }}"
  issuerRef:
    name: http-01-staging
    kind: ClusterIssuer
{{- end }}
