{{- if .Values.selfSignedCertificate.enabled }}
{{- if .Values.selfSignedCertificate.generateCA }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
spec:
  commonName: ca.kuberise.local
  isCA: true
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  secretName: ca-key-pair
  duration: 24000h # 1000 days
  renewBefore: 360h # 15 days
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-clusterissuer
spec:
  ca:
    secretName: {{ if .Values.selfSignedCertificate.generateCA }}ca-key-pair{{ else }}ca-key-pair-external{{ end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-default-crt
  namespace: cert-manager
spec:
  secretName: wildcard-tls
  dnsNames:
    - "*.{{ .Values.global.domain }}"
  issuerRef:
    name: selfsigned-clusterissuer
    kind: ClusterIssuer
---
{{- end }}
