apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: project1-dev
  sources:
  - repoURL: https://airflow.apache.org
    chart: apache-airflow/airflow
    targetRevision: 1.10.0
    helm:
      releaseName: airflow
      valueFiles:
        - $values/app-values/airflow/airflow-values-project1-dev.yaml
  - repoURL: https://github.com/Kuberise/kuberise.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        managed: "true"
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
      retry:
        limit: 3
        backoff:
          duration: 30
          factor: 2
          maxDuration: 60