apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: project1-dev
  sources:
  - repoURL: registry-1.docker.io/bitnamicharts/keycloak
    chart: keycloak
    targetRevision: 22.0.1
    helm:
      releaseName: keycloak
      valueFiles:
        - $values/app-values/keycloak/keycloak-values-project1-dev.yaml
  - repoURL: https://github.com/Kuberise/kuberise.git
    targetRevision: mojtaba/folder-structure
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        managed: "true"
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
      retry:
        limit: 3
        backoff:
          duration: 30
          factor: 2
          maxDuration: 60
