# placeholder for more security tools
ArgocdApplications:

  sealed-secrets:
    enabled: false

  vault:
    enabled: false
    repoURL: https://helm.releases.hashicorp.com
    namespace: vault
    targetRevision: 0.28.0
    chart: vault

  secrets-manager:
    enabled: false

  clair:
    enabled: false
