vcluster:
  controlPlane:
    ingress:
      enabled: true
      # Host is the host where vCluster will be reachable
      host: vcluster.onprem.kuberise.dev
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      spec:
        ingressClassName: nginx-external
        tls:
          - hosts:
              - vcluster.onprem.kuberise.dev
  exportKubeConfig:
    context: vcluster
    server: vcluster.onprem.kuberise.dev
    secret:
      # Name is the name of the secret where the kubeconfig should get stored.
      name: ""
      # Namespace where vCluster should store the kubeconfig secret. If this is not equal to the namespace
      # where you deployed vCluster, you need to make sure vCluster has access to this other namespace.
      namespace: ""
