apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton
spec:
  ingressClassName: nginx-external
  rules:
  - host: tekton.{{ .Values.global.domain }}
    http:
      paths:
      - backend:
          service:
            name: edp-tekton-dashboard
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - tekton.{{ .Values.global.domain }}
