apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: dev-shared-onprem
servers: 1
agents: 0
network: kuberise
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: true
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      # - arg: --disable=servicelb # No need for metallb in k3d, because ServiceLB does the same job
      #   nodeFilters:
      #     - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
env:
  - envVar: HTTP_PROXY=http://registry-proxy:3128
    nodeFilters:
      - all
  - envVar: HTTPS_PROXY=http://registry-proxy:3128
    nodeFilters:
      - all
  - envVar: NO_PROXY='localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.local,.svc'
    nodeFilters:
      - all
volumes:
  - volume: __HOME_DIR__/docker_registry_proxy/certs/ca.crt:/etc/ssl/certs/registry-proxy-ca.pem
    nodeFilters:
      - all
  # Add this volume mount to keep container image storage when you delete and recreate the cluster
  - volume: __HOME_DIR__/tmp/k3d_docker_images:/var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content
    nodeFilters:
      - all
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
      - loadbalancer
