image:
  tag: latest

replicaCount: 3

env:
  Environment: dev
  name: show-env
  PROTOCOL: HTTP

useHttps: false

containerPorts:
  http: 80

service:
  type: ClusterIP
  ports:
    http: 80

# sample http probes
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
startupProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 30

ingress:
  className: nginx-external
