apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database
spec:
  instances: 1

  bootstrap:
    initdb:
      database: app
      owner: application
      secret:
        name: database-app

  storage:
    size: 2Gi

  monitoring:
    enablePodMonitor: true

  enableSuperuserAccess: true
  superuserSecret:
    name: database-superuser

  managed:
    roles:
    - name: application
      createdb: true
      login: true
      connectionLimit: -1
      ensure: present
      inherit: true
