ollama:
  ingress:
    enabled: true
    className: nginx-external
    hosts:
      - host: ollama.onprem.kuberise.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - ollama.onprem.kuberise.dev
  ollama:
    models:
      pull:
        - deepseek-r1:1.5b
      run:
        - deepseek-r1:1.5b

  persistentVolume:
    enabled: true

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 60
