ollama:
  ingress:
    enabled: true
    className: nginx-external
    hosts:
      - host: ollama.onprem.kuberise.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - ollama.onprem.kuberise.dev
  replicaCount: 1
  ollama:
    models:
      pull:
        - deepseek-r1:1.5b
        - gemma3:4b
        - llama3.2:3b
      run:
        - deepseek-r1:1.5b

  persistentVolume:
    enabled: true

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

# TODO: Retain the PV when disable Ollama to keep the downloaded models
