apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  # Name of the MinIO tenant
  name: minio
  # Namespace where the tenant will be deployed
  namespace: default
spec:
  # MinIO version to be deployed (required)
  image: minio/minio:RELEASE.2023-06-19T19-52-50Z

  # Number of MinIO servers/pods
  replicas: 1

  # Secret for MinIO credentials (required)
  credsSecret:
    name: minio-creds-secret

  # Storage configuration (required)
  pools:
    - servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
