apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  # Name of the MinIO tenant
  name: minio
  # Namespace where the tenant will be deployed
  namespace: default
  labels:
    app: minio
spec:
  # MinIO version to be deployed
  image: minio/minio:RELEASE.2023-06-19T19-52-50Z
  imagePullPolicy: IfNotPresent

  # Number of MinIO servers/pods in this tenant
  replicas: 1

  # Mount path where PersistentVolumes will be mounted in the container
  mountPath: "/export"

  # Access keys for the MinIO tenant
  credsSecret:
    name: minio-creds-secret

  # PodManagement policy for MinIO pods
  podManagementPolicy: Parallel

  # Storage configuration
  pools:
    - servers: 1
      # Number of volumes per server
      volumesPerServer: 1
      # Volume claim template for persistent storage
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          # Uncomment to specify storage class
          # storageClassName: standard

  # External service configuration
  serviceMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/minio/v2/metrics/cluster"
      prometheus.io/port: "9000"

  # Resource requirements
  resources:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: 1

  # Define console configuration
  console:
    # Console image details
    image: minio/console:v0.22.0
    # Number of console replicas
    replicas: 1
    # Console credentials secret
    consoleSecret:
      name: console-secret
    # Resource requirements for console
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

  # Liveness probe configuration
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

  # Readiness probe configuration
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

  # Security context for pods
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  # Prometheus metrics configuration
  metrics:
    enabled: true

  # Environment variables for MinIO containers
  env:
    - name: MINIO_BROWSER
      value: "on"
    - name: MINIO_COMPRESS
      value: "true"
    - name: MINIO_COMPRESS_EXTENSIONS
      value: ".pdf,.doc,.docx,.xlsx,.xls,.ppt,.pptx"
