rancher:
  ingress:
    enabled: true
    ingressClassName: nginx-external

    tls:
      # options: rancher, letsEncrypt, secret
      source: secret
      secretName: "" # to use default whildcard cert in nginx-ingress

  replicas: 1

  systemDefaultRegistry: ""

  # Set a bootstrap password. If leave empty, a random password will be generated.
  bootstrapPassword: ""
