apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.global.clusterName }}
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  sourceRepos:
    - '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: {{ .Values.global.spec.destination.server }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
