
useHttps: true

# env:
  # PORT: 443

containerPorts:
  https: 8080

service:
  type: ClusterIP
  ports:
    https: 8080

ingress:
  className: nginx-external
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    cert-manager.io/cluster-issuer: "selfsigned"
