apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/shared: "false"
  name: loki-loki-distributed-gateway
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  # No selector needed - ClusterMesh will sync endpoints from the shared cluster
  # where Loki pods are actually running
  type: ClusterIP
