{{- if .Values.letsencryptProductionCertificate.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-01-production
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-01-production
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx-external
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-default-crt-letsencrypt-production
  namespace: cert-manager
spec:
  secretName: wildcard-tls-letsencrypt-production
  dnsNames:
  {{- range .Values.subdomains }}
  - "{{ . }}.{{ $.Values.domain }}"
  {{- end }}
  issuerRef:
    name: http-01-production
    kind: ClusterIssuer
{{- end }}
