{{- if .Values.selfSignedCertificate.enabled }}
{{- if .Values.selfSignedCertificate.generateCA }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# certificate for the CA
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
spec:
  commonName: ca.kuberise.local
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
  secretName: ca-key-pair
  duration: 24000h # 1000 days
  renewBefore: 360h # 15 days
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  ca:
    secretName: {{ if .Values.selfSignedCertificate.generateCA }}ca-key-pair{{ else }}ca-key-pair-external{{ end }}
---
# certificate for the platform services and applications
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-default-crt-selfsigned
  namespace: cert-manager
spec:
  secretName: ssl-certificate-selfsigned
  dnsNames:
    - "*.{{ .Values.global.domain }}"
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
{{- end }}
