image:
  tag: latest

autoscaling:
  enabled: false
replicaCount: 1

env:
  Environment: dev
  name: show-env
  PROTOCOL: HTTP

useHttps: false

containerPorts:
  http: 80

service:
  type: ClusterIP
  ports:
    http: 80
  targetPort: 80


# sample http probes
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
startupProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 30

ingress:
  className: nginx-external
  # annotations: # enable this when you want to use oauth2-proxy
  #   nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.{{ .Values.global.domain }}/oauth2/start"
  #   nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.{{ .Values.global.domain }}/oauth2/auth
