apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-database
  namespace: cloudnative-pg
spec:
  instances: 1

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cnpg-database-app

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  enableSuperuserAccess: true
  superuserSecret:
    name: cnpg-database-superuser

  managed:
    roles:
    - name: app
      createdb: true
      login: true
      connectionLimit: -1
      ensure: present
      inherit: true
