# the only source that should be used in external ingress-nginx service.
# because it is the only one that is exposed to the internet
# and there should be only one wildcard dns record for the external ingress-nginx service.
sources:
  - service # only external ingress service needs dns translation
provider:
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare
        key: cloudflare_api_token
extraArgs:
  cloudflare-proxied: "false"
policy: sync
txtOwnerId: "dev-shared-onprem-externaldns"
txtPrefix: "externaldns"
interval: "1m"
logLevel: info
